# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='cursos.Curso'),
        ),
    ]
